spring.application.name=AiFinancialReport
spring.ai.bedrock.aws.region=us-east-1

#spring.ai.bedrock.converse.chat.options.model=us.anthropic.claude-haiku-4-5-20251001-v1:0
spring.ai.bedrock.aws.timeout=10m

spring.ai.model.embedding=bedrock-titan